package system_test

import (
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// setupCompatRepo initialises a bare repo, creates a data directory at
// goalieHome/data, populates it with files from fixtureDir, and pushes to the
// bare repo so that goalie pull works during the test.
func setupCompatRepo(t *testing.T, fixtureDir, bareRepo, gitHomeDir, goalieHome string) {
	t.Helper()
	dataDir := filepath.Join(goalieHome, "data")
	if err := os.MkdirAll(dataDir, 0755); err != nil {
		t.Fatal(err)
	}
	runGitInDir(t, dataDir, gitHomeDir, "init")
	runGitInDir(t, dataDir, gitHomeDir, "symbolic-ref", "HEAD", "refs/heads/data")
	runGitInDir(t, dataDir, gitHomeDir, "remote", "add", "origin", bareRepo)
	if err := copyDirContents(fixtureDir, dataDir); err != nil {
		t.Fatalf("copy fixture: %v", err)
	}
	runGitInDir(t, dataDir, gitHomeDir, "add", "-A")
	runGitInDir(t, dataDir, gitHomeDir, "commit", "-m", "compat: load fixture")
	runGitInDir(t, dataDir, gitHomeDir, "push", "--set-upstream", "origin", "data")
}

func runGitInDir(t *testing.T, dir, gitHomeDir string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "HOME="+gitHomeDir)
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git %v in %s: %v\n%s", args, dir, err, out)
	}
}

func copyDirContents(src, dst string) error {
	return filepath.WalkDir(src, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(src, path)
		target := filepath.Join(dst, rel)
		if d.IsDir() {
			return os.MkdirAll(target, 0755)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		return os.WriteFile(target, data, 0644)
	})
}

// suppressDailyCheck writes a state.json marking the version check as just
// completed so that checkVersionOnce does not run during the test. This keeps
// committed fixture data unmodified by version-recording side effects.
func suppressDailyCheck(t *testing.T, goalieHome string) {
	t.Helper()
	s := fmt.Sprintf(`{"last_version_check":"%s"}`, time.Now().UTC().Format(time.RFC3339))
	if err := os.WriteFile(filepath.Join(goalieHome, "state.json"), []byte(s), 0644); err != nil {
		t.Fatal(err)
	}
}

func assertMatchesGolden(t *testing.T, got, goldenPath string) {
	t.Helper()
	want, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read golden file %s: %v", goldenPath, err)
	}
	if strings.TrimSpace(got) != strings.TrimSpace(string(want)) {
		t.Errorf("export output does not match golden file %s\ngot:\n%s\nwant:\n%s",
			goldenPath, got, string(want))
	}
}

// ── plaintext v1.0.0 ────────────────────────────────────────────────────────

func TestCompat_Plaintext_V1_0_0(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping compatibility test in short mode")
	}

	repo := setupBareRepo(t)
	gh := gitHome(t)
	goalieHome := t.TempDir()

	if err := os.WriteFile(
		filepath.Join(goalieHome, "config.json"),
		[]byte(`{"name":"@alice"}`), 0644,
	); err != nil {
		t.Fatal(err)
	}

	setupCompatRepo(t,
		"testdata/compat/plaintext-v1.0.0/data",
		repo, gh, goalieHome,
	)
	suppressDailyCheck(t, goalieHome)

	out := runGoalie(t, goalieHome, gh, "", "export")
	assertMatchesGolden(t, out, "testdata/compat/plaintext-v1.0.0/export.golden.jsonl")
}

// ── plaintext pre-versioning ─────────────────────────────────────────────────

// TestCompat_Plaintext_Pre_Versioning verifies that goalie can read a database
// created before schema versioning was introduced: no versions/ directory and
// no schema_version field in journal entries.
func TestCompat_Plaintext_Pre_Versioning(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping compatibility test in short mode")
	}

	repo := setupBareRepo(t)
	gh := gitHome(t)
	goalieHome := t.TempDir()

	if err := os.WriteFile(
		filepath.Join(goalieHome, "config.json"),
		[]byte(`{"name":"@alice"}`), 0644,
	); err != nil {
		t.Fatal(err)
	}

	setupCompatRepo(t,
		"testdata/compat/plaintext-pre-versioning/data",
		repo, gh, goalieHome,
	)
	suppressDailyCheck(t, goalieHome)

	out := runGoalie(t, goalieHome, gh, "", "export")
	assertMatchesGolden(t, out, "testdata/compat/plaintext-pre-versioning/export.golden.jsonl")
}

// ── encrypted v1.0.0 ─────────────────────────────────────────────────────────

// TestCompat_Encrypted_V1_0_0 verifies that goalie can export from a committed
// encrypted v1.0.0 fixture. The fixture was generated by tests/compat/generate-data.sh
// with --encrypted; encryption_key.hex and key-check.enc are committed so the
// key-check SHA256 in the golden file is stable across runs.
func TestCompat_Encrypted_V1_0_0(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping compatibility test in short mode")
	}

	repo := setupBareRepo(t)
	gh := gitHome(t)
	goalieHome := t.TempDir()

	// Install the committed encryption key so goalie can decrypt the fixture.
	keyHex, err := os.ReadFile("testdata/compat/encrypted-v1.0.0/test_encryption_key.hex")
	if err != nil {
		t.Fatalf("read encryption_key.hex: %v", err)
	}
	if err := os.WriteFile(
		filepath.Join(goalieHome, "encryption.key"),
		bytes.TrimSpace(keyHex), 0600,
	); err != nil {
		t.Fatal(err)
	}

	setupCompatRepo(t,
		"testdata/compat/encrypted-v1.0.0/data",
		repo, gh, goalieHome,
	)
	suppressDailyCheck(t, goalieHome)

	out := runGoalie(t, goalieHome, gh, "", "export")
	assertMatchesGolden(t, out, "testdata/compat/encrypted-v1.0.0/export.golden.jsonl")
}
